version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
      tag: 12.19.0
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Build application
                command: npm install
            - run: sudo npm install -g serverless
  test:
    executor:
      name: node/default
      tag: 12.19.0
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Test application
                command: npm run test
            - store_artifacts:
                path: __tests__/coverage
  deploy_prod:
    executor:
      name: node/default
      tag: 12.19.0
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Deploy application prod
                command: |
                  chmod +x .circleci/scripts/deploy.sh
                  source .circleci/scripts/deploy.sh
            - run: sudo npm install -g serverless
            - run: npm run deploy:prod

workflows:
  development_build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - main
      - test:
          requires:
            - build
  production_build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - test:
          requires:
            - build
      - deploy_prod:
          context: PROD
          requires:
            - test
            - build 